permalink: /:year/:month/:day/:title 

pygments: true

title : Three Sisters
tagline: We only grow together.
author :
  name : Three Sisters
  email : ngunner@threesisters.us
  github : Three-Sisters
  twitter : threesistersus
  web : http://www.threesisters.us

production_url : http://Three-Sisters.github.io/

version : 0.1.0

baseurl : http://Three-Sisters.github.io/

 
comments :
  provider : disqus
  disqus :
    short_name : canopymaps
   
   
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-xxxxxxxx-x'

  
authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: Three Sisters US LLC Founder & CEO
    gravatar: http://www.gravatar.com/avatar/a85d870dce3cc177b6b0016a1ef4c200.png
    email: ngunner@threesisters.us
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
  pjackino:
    name: Paul Jackino
    display_name: Paul Jackino
    bio: Three Ststers farmer relations, operations manager, and food specialist.
    gravatar:
    email:
    web:
    twitter:
    github:
    
  
timezone : America/New_York
